In [ ]:
import numpy as np
ar = np.array([1, 2, 3, 4, 5])
ar2 = np.array([6, 7, 8, 9, 10])
print(ar + ar2)
print( ar - ar2)
print(ar *ar2)
print(ar/ar2)
print(np.add(ar ,ar2))
print(np.subtract(ar,ar2))
print(np.multiply(ar,ar2))
print(np.divide(ar,ar2))

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
ar3 = np.array([[1,2,3] , [4,5,6]])
print(ar3 *2)

In [ ]:
ar3 = np.array([[1,2] , [5,6]])
ar4 = np.array([[6,7] ,[10,11]])
mat = np.matmul(ar3,ar4)
print(mat)
mat1 = ar3 @ ar4
print(mat1)
print(ar3.sum())
print(ar3.max())
print(ar3.min())
print(ar3.mean())
print(ar3)


[[ 26  29]
 [ 90 101]]
[[ 26  29]
 [ 90 101]]
14
6
1
3.5
[[1 2]
 [5 6]]


In [ ]:
a = np.array([20,200,45,100,70])
print(a[a>=60])

[200 100  70]


In [ ]:
b= np.array([10, 60, 25, 80, 45, 90, 30, 75])
c = []
for i in b:
   if i > 50:
        c.append(i)
c = np.array(c)

print( b)
print( c)

[10 60 25 80 45 90 30 75]
[60 80 90 75]


In [ ]:
import pandas as pd

In [ ]:
d = pd.Series([10,20,30,40])
print(d)

0    10
1    20
2    30
3    40
dtype: int64


In [ ]:
df = pd.Series({"days":420,"day2":380})

print(df)
df.shape
df.head()

days    420
day2    380
dtype: int64


,0
days,420
day2,380


In [ ]:
data = {
    'calories': [420, 380, 390],
    'duration': [50, 40, 45]
}
df1 = pd.DataFrame(data)
print(df1)


   calories  duration
0       420        50
1       380        40
2       390        45


In [ ]:
data1 ={
    'name' : ["Aditya","chetna"],
    'age' :[21,21],

    'city' : ["dehradun","dehradun"]
}
df2 = pd.DataFrame(data1)
df2.index = ["person1","person2"]
print(df2)


           name  age      city
person1  Aditya   21  dehradun
person2  chetna   21  dehradun


In [1]:

!git clone https://github.com/addy01l/lecture.git


Cloning into 'lecture'...
fatal: could not read Username for 'https://github.com': No such device or address


In [2]:
git init

SyntaxError: invalid syntax (2830201818.py, line 1)