<a href="https://colab.research.google.com/github/addy01l/lecture/blob/main/MLlab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
ar = np.array([1, 2, 3, 4, 5])
ar2 = np.array([6, 7, 8, 9, 10])
print(ar + ar2)
print( ar - ar2)
pricant(ar *ar2)
print(ar/ar2)
print(np.add(ar ,ar2))
print(np.subtract(ar,ar2))
print(np.multiply(ar,ar2))
print(np.divide(ar,ar2))

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
ar3 = np.array([[1,2,3] , [4,5,6]])
print(ar3 *2)

In [ ]:
ar3 = np.array([[1,2] , [5,6]])
ar4 = np.array([[6,7] ,[10,11]])
mat = np.matmul(ar3,ar4)
print(mat)
mat1 = ar3 @ ar4
print(mat1)
print(ar3.sum())
print(ar3.max())
print(ar3.min())
print(ar3.mean())
print(ar3)


[[ 26  29]
 [ 90 101]]
[[ 26  29]
 [ 90 101]]
14
6
1
3.5
[[1 2]
 [5 6]]


In [ ]:
a = np.array([20,200,45,100,70])
print(a[a>=60])

[200 100  70]


In [ ]:
b= np.array([10, 60, 25, 80, 45, 90, 30, 75])
c = []
for i in b:
   if i > 50:
        c.append(i)
c = np.array(c)

print( b)
print( c)

[10 60 25 80 45 90 30 75]
[60 80 90 75]


In [ ]:
import pandas as pd

In [ ]:
d = pd.Series([10,20,30,40])
print(d)

0    10
1    20
2    30
3    40
dtype: int64


In [ ]:
df = pd.Series({"days":420,"day2":380})

print(df)
df.shape
df.head()

days    420
day2    380
dtype: int64


,0
days,420
day2,380


In [ ]:
data = {
    'calories': [420, 380, 390],
    'duration': [50, 40, 45]
}
df1 = pd.DataFrame(data)
print(df1)


   calories  duration
0       420        50
1       380        40
2       390        45


In [ ]:
data1 ={
    'name' : ["Aditya","chetna"],
    'age' :[21,21],

    'city' : ["dehradun","dehradun"]
}
df2 = pd.DataFrame(data1)
df2.index = ["person1","person2"]
print(df2)


           name  age      city
person1  Aditya   21  dehradun
person2  chetna   21  dehradun


In [ ]:
import pandas as pd
data = pd.read_csv('/content/Untitled spreadsheet - fruit_tasty_data.csv')
h = None
for r in data.values:
    if r[-1] == "Yes":
        if h is None:
            h = r[:-1].copy()
        else:
            for i in range(4):
                if h[i] != r[i]:
                    h[i] = "?"

print("Hfinal:", h)

Hfinal: ['?' '?' 'Smooth' '?']


Using Numpy


In [ ]:
import numpy as np

data = np.genfromtxt(
    '/content/Untitled spreadsheet - fruit_tasty_data.csv',
    delimiter=',',
    dtype=str,
    skip_header=1
)

h = None

for row in data:
    if row[-1] == "Yes":
        if h is None:
            h = row[:-1].copy()
        else:
            for i in range(4):
                if h[i] != row[i]:
                    h[i] = "?"

print("Hypothesis:", h)

Hypothesis: ['?' '?' 'Smooth' '?']


In [ ]:
data = [
    ['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same','same', 'Yes'],
    ['Sunny', 'Warm', 'High', 'Strong', 'Warm', 'Same', 'same','Yes'],
    ['Rainy', 'Cold', 'High', 'Strong', 'Warm', 'Change','change', 'No'],
    ['Sunny', 'Warm', 'High', 'Strong', 'Cool', 'Change','change' ,'Yes']
]

n = len(data[0]) - 1

S = ['0'] * n
G = [['?'] * n]

for row in data:
    x = row[:-1]
    y = row[-1]

    if y == 'Yes':
        for i in range(n):
            if S[i] == '0':
                S[i] = x[i]
            elif S[i] != x[i]:
                S[i] = '?'

        G = [g for g in G if all(g[i] == '?' or g[i] == S[i] for i in range(n))]

    else:
        new_g = []

        for g in G:
            for i in range(n):
                if g[i] == '?' and S[i] != '?' and S[i] != x[i]:
                    h = g.copy()
                    h[i] = S[i]
                    new_g.append(h)

        G = new_g

print("Specific:", S)
print("General:", G)

Specific: ['Sunny', 'Warm', '?', 'Strong', '?', '?', '?']
General: [['Sunny', '?', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?', '?']]


In [ ]:
data = [
    ['Small', 'Red', 'Round', 'Yes'],
    ['Small', 'Blue', 'Round', 'Yes'],
    ['Large', 'Red', 'Square', 'No'],
    ['Small', 'Blue', 'Square', 'Yes']
]


n = len(data[0]) - 1

S = ['0'] * n
G = [['?'] * n]

for row in data:
    x = row[:-1]
    y = row[-1]

    if y == 'Yes':
        for i in range(n):
            if S[i] == '0':
                S[i] = x[i]
            elif S[i] != x[i]:
                S[i] = '?'

        G = [g for g in G if all(g[i] == '?' or g[i] == S[i] for i in range(n))]

    else:
        new_g = []

        for g in G:
            for i in range(n):
                if g[i] == '?' and S[i] != '?' and S[i] != x[i]:
                    h = g.copy()
                    h[i] = S[i]
                    new_g.append(h)

        G = new_g

print("Specific:", S)
print("General:", G)

Specific: ['Small', '?', '?']
General: [['Small', '?', '?']]


In [4]:
import csv
from collections import defaultdict

def load_data(filepath):
    with open(filepath, 'r') as file:
        reader = csv.reader(file)
        data = list(reader)

    return data[0], data[1:]


def train_naive_bayes(data):
    class_count = defaultdict(int)
    feature_count = defaultdict(lambda: defaultdict(int))
    feature_values = defaultdict(set)

    for row in data:
        features = row[:-1]
        label = row[-1]

        class_count[label] += 1

        for i, value in enumerate(features):
            feature_count[label][(i, value)] += 1
            feature_values[i].add(value)

    return class_count, feature_count, feature_values


def predict(row, class_count, feature_count, feature_values, total):
    best_class = None
    best_probability = -1

    for label in class_count:
        probability = class_count[label] / total

        for i, value in enumerate(row):
            count = feature_count[label].get((i, value), 0)

            probability *= (
                count + 1
            ) / (class_count[label] + len(feature_values[i]))

        if probability > best_probability:
            best_probability = probability
            best_class = label

    return best_class


# Load training data
header, train_data = load_data("/content/data11.csv")

# Train model
class_count, feature_count, feature_values = train_naive_bayes(train_data)

# Test data
test_data = [
    ["Sunny", "Cool", "High", "True", "No"],
    ["Overcast", "Mild", "High", "False", "Yes"],
    ["Rain", "Cool", "Normal", "False", "Yes"],
    ["Sunny", "Mild", "Normal", "True", "Yes"],
    ["Rain", "Mild", "High", "True", "No"],
]

correct = 0

print("Predictions")
print("-" * 40)

for row in test_data:
    features = row[:-1]
    actual = row[-1]

    predicted = predict(
        features, class_count, feature_count, feature_values, len(train_data)
    )

    print("Actual:", actual, "| Predicted:", predicted)

    if actual == predicted:
        correct += 1

accuracy = (correct / len(test_data)) * 100

print("-" * 40)
print("Correct Predictions:", correct)
print("Total Test Cases:", len(test_data))
print("Accuracy:", accuracy, "%")

Predictions
----------------------------------------
Actual: No | Predicted: No
Actual: Yes | Predicted: Yes
Actual: Yes | Predicted: Yes
Actual: Yes | Predicted: Yes
Actual: No | Predicted: No
----------------------------------------
Correct Predictions: 5
Total Test Cases: 5
Accuracy: 100.0 %


In [9]:
import pandas as pd
import math

data = pd.read_csv("/content/gender_height_weight.csv")
male = data[data["Gender"] == "M"]
female = data[data["Gender"] == "F"]
def gaussian(x, mean, variance):
    return (1 / math.sqrt(2 * math.pi * variance)) * \
           math.exp(-((x - mean) ** 2) / (2 * variance))


male_hmean = male["Height"].mean()
male_hvar = male["Height"].var()

male_wmean = male["Weight"].mean()
male_wvar = male["Weight"].var()

female_hmean = female["Height"].mean()
female_hvar = female["Height"].var()

female_wmean = female["Weight"].mean()
female_wvar = female["Weight"].var()
def predict(height, weight):

    male_prob = (
        0.5 *
        gaussian(height, male_h_mean, male_h_var) *
        gaussian(weight, male_w_mean, male_w_var)
    )

    female_prob = (
        0.5 *
        gaussian(height, female_h_mean, female_h_var) *
        gaussian(weight, female_w_mean, female_w_var)
    )

    if male_prob > female_prob:
        return "Male"
    else:
        return "Female"


test_data = [
    [178, 75, "Male"],
    [160, 52, "Female"],
    [180, 80, "Male"],
    [158, 48, "Female"],
    [172, 68, "Male"],
    [165, 55, "Female"]
]

correct = 0

for height, weight, actual in test_data:

    predicted = predict(height, weight)

    print(
        "Height:", height,
        "Weight:", weight,
        "Actual:", actual,
        "Predicted:", predicted
    )

    if predicted == actual:
        correct += 1


accuracy = correct / len(test_data) * 100
print("Total:", len(test_data))
print("Accuracy:", accuracy, "%")

height = float(input("\nEnter Height: "))
weight = float(input("Enter Weight: "))

print("Predicted:", predict(height, weight))

Height: 178 Weight: 75 Actual: Male Predicted: Male
Height: 160 Weight: 52 Actual: Female Predicted: Female
Height: 180 Weight: 80 Actual: Male Predicted: Male
Height: 158 Weight: 48 Actual: Female Predicted: Female
Height: 172 Weight: 68 Actual: Male Predicted: Male
Height: 165 Weight: 55 Actual: Female Predicted: Female
Total: 6
Accuracy: 100.0 %

Enter Height: 123
Enter Weight: 54
Predicted: Female
